// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import config from "./deno.json" assert { type: "json" };
import * as $0 from "./routes/[pageNotFound].tsx";
import * as $1 from "./routes/_404.tsx";
import * as $2 from "./routes/_app.tsx";
import * as $3 from "./routes/api/graphqlGateway.ts";
import * as $4 from "./routes/index.tsx";
import * as $5 from "./routes/products/[product].tsx";
import * as $$0 from "./islands/AddToCart.tsx";
import * as $$1 from "./islands/Cart.tsx";
import * as $$2 from "./islands/PageNotFoundCounter.tsx";
import * as $$3 from "./islands/ProductDetails.tsx";
import * as $$4 from "./islands/RedirectTo404.tsx";

const manifest = {
  routes: {
    "./routes/[pageNotFound].tsx": $0,
    "./routes/_404.tsx": $1,
    "./routes/_app.tsx": $2,
    "./routes/api/graphqlGateway.ts": $3,
    "./routes/index.tsx": $4,
    "./routes/products/[product].tsx": $5,
  },
  islands: {
    "./islands/AddToCart.tsx": $$0,
    "./islands/Cart.tsx": $$1,
    "./islands/PageNotFoundCounter.tsx": $$2,
    "./islands/ProductDetails.tsx": $$3,
    "./islands/RedirectTo404.tsx": $$4,
  },
  baseUrl: import.meta.url,
  config,
};

export default manifest;
